custom:
  bert_base_path: !!python/object/apply:pathlib.WindowsPath
  - modules
  - chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: !!python/object/apply:pathlib.WindowsPath
  - modules
  - chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: !!python/object/apply:pathlib.WindowsPath
  - models
  - '1'
  - jvnv_f1-e15.ckpt
  version: v2
  vits_weights_path: !!python/object/apply:pathlib.WindowsPath
  - models
  - '1'
  - jvnv_f1_e8_s480.pth
default:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  version: v1
  vits_weights_path: GPT_SoVITS/pretrained_models/s2G488k.pth
default_v2:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  version: v2
  vits_weights_path: GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
